### ISSUE TITLE
Add support for running natively on apple silicon arm64

### ISSUE THREAD

**Issue by KasperOazo** [pyca/pyopenssl#1118] opened 2022-04-27 09:02 UTC
When trying to run the snowflake library (snowflake-connector-python) natively on an apple silicon computer via miniforge3 (https://github.com/conda-forge/miniforge) I get this error:

MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks

The error seems to be related to the pyopenssl libary.
Would be really good to get this library running natively also :)

**Comment by alex** [comment] 2022-04-27 11:04
We _do_ support Apple Sillicon, we're not sure why some users get this error message. Closing as a duplicate of https://github.com/pyca/pyopenssl/issues/873, which may contain some help.

**Closed by alex** 2022-04-27 11:04 UTC
