### ISSUE TITLE
_lib.RSA_print(bio, rsa, 0) causes segmentation fault

### ISSUE THREAD

**Issue by abrahammartin** [pyca/pyopenssl#259] opened 2015-05-13 13:34 UTC
_lib.RSA_print(bio, rsa, 0) in crypto.py 

crashes with a "Segmentation fault: 11" [1] when executing dump_privatekey for the following x509req:

-----BEGIN CERTIFICATE REQUEST-----
MIICoTCCAmECAQAwgZ8xCzAJBgNVBAYTAkdCMRAwDgYDVQQIEwdFbmdsYW5kMRIw
EAYDVQQHEwlDYW1icmlkZ2UxJDAiBgNVBAoTG1RoZSBVbml2ZXJzaXR5IG9mIENh
bWJyaWRnZTEcMBoGA1UECxMTQ29tcHV0ZXIgTGFib3JhdG9yeTEmMCQGA1UEAxMd
d3d3LnB1YmxpY2F0aW9ucy5jbC5jYW0uYWMudWswggG2MIIBKwYHKoZIzjgEATCC
AR4CgYEAo0S4k91lqRq0HyBsHGeWRoJeoWSTmKD6Y5E7vYOOPeTMlGKAZf0UPrDm
5g2oQboWiBUoDs1TQ3f6M9pIhDPrJO9HR2PFKcaw07lopMmaftRmA8D8ktX/RmnC
XSTZ9kzvzI1zAAa9oVAs0MNpZhm05NCKiwn7h0slNz0z/3n3rL0CFQDrPJBz1lFD
+Y/VvJBQoqxxpHi6PQKBgEN24afjpBkD/ZaBgSAIPsMGTAqFVWZaAzuhqGIyxPpG
1vK4HcvPLC2ypCLb6antLYbKHTffL9Wcx9HVLjf8FIt6Yv/VgbObpY86pzmkdCzi
3ndEstMtXjRbbTog2dd2Dh95U3mqHw3Z8ScmxGSHguS64vg4CjN/XmRMBZujnCyK
A4GEAAKBgHPeYvecW6LPeC+o0Ceuz4bqIsXJHsbC8tKwBBppeM/ETrMybsehtPbd
TivaYJFzAoJgTAptIxF1n3f22FzNtpNzd8XDNAbUQm1lsIX5ySed3xn+Mwagqr5I
jsdB1ywrrj/d9/Ha9jyG6lNh3uKTwqUBr/7XU/SWNLjYLefPFgDPoAAwCQYHKoZI
zjgEAwMvADAsAhR7S2+G3gObSZ+XG953HJqC0YkWogIUWdPkEHtY1cID6xNEcjK4
yvb2luU=
-----END CERTIFICATE REQUEST-----

I'm using OSX 10.10.3 with Python 2.7.5

[1] SIGSEGV      11       Core    Invalid memory reference
extracted from http://man7.org/linux/man-pages/man7/signal.7.html

**Comment by alex** [comment] 2015-05-13 13:44
Are you able to trigger this using the pyOpenSSL API, or just by using the OpenSSL binding directly?

**Comment by abrahammartin** [comment] 2015-05-13 14:01
Using crypto.dump_privatekey(crypto.FILETYPE_TEXT, x509.get_pubkey())

works fine with FILETYPE_PEM

**Comment by alex** [comment] 2015-05-13 14:07
Crashing example:

```
from OpenSSL import crypto

CERT = """
-----BEGIN CERTIFICATE REQUEST-----
MIICoTCCAmECAQAwgZ8xCzAJBgNVBAYTAkdCMRAwDgYDVQQIEwdFbmdsYW5kMRIw
EAYDVQQHEwlDYW1icmlkZ2UxJDAiBgNVBAoTG1RoZSBVbml2ZXJzaXR5IG9mIENh
bWJyaWRnZTEcMBoGA1UECxMTQ29tcHV0ZXIgTGFib3JhdG9yeTEmMCQGA1UEAxMd
d3d3LnB1YmxpY2F0aW9ucy5jbC5jYW0uYWMudWswggG2MIIBKwYHKoZIzjgEATCC
AR4CgYEAo0S4k91lqRq0HyBsHGeWRoJeoWSTmKD6Y5E7vYOOPeTMlGKAZf0UPrDm
5g2oQboWiBUoDs1TQ3f6M9pIhDPrJO9HR2PFKcaw07lopMmaftRmA8D8ktX/RmnC
XSTZ9kzvzI1zAAa9oVAs0MNpZhm05NCKiwn7h0slNz0z/3n3rL0CFQDrPJBz1lFD
+Y/VvJBQoqxxpHi6PQKBgEN24afjpBkD/ZaBgSAIPsMGTAqFVWZaAzuhqGIyxPpG
1vK4HcvPLC2ypCLb6antLYbKHTffL9Wcx9HVLjf8FIt6Yv/VgbObpY86pzmkdCzi
3ndEstMtXjRbbTog2dd2Dh95U3mqHw3Z8ScmxGSHguS64vg4CjN/XmRMBZujnCyK
A4GEAAKBgHPeYvecW6LPeC+o0Ceuz4bqIsXJHsbC8tKwBBppeM/ETrMybsehtPbd
TivaYJFzAoJgTAptIxF1n3f22FzNtpNzd8XDNAbUQm1lsIX5ySed3xn+Mwagqr5I
jsdB1ywrrj/d9/Ha9jyG6lNh3uKTwqUBr/7XU/SWNLjYLefPFgDPoAAwCQYHKoZI
zjgEAwMvADAsAhR7S2+G3gObSZ+XG953HJqC0YkWogIUWdPkEHtY1cID6xNEcjK4
yvb2luU=
-----END CERTIFICATE REQUEST-----
"""

c = crypto.load_certificate_request(crypto.FILETYPE_PEM, CERT)
crypto.dump_privatekey(crypto.FILETYPE_TEXT, c.get_pubkey())
```

I think this might be caused because you're passing a public key to a function which expects a private key? Not sure, we should test.

In any event, confirmed that this is a bug.

**Comment by abrahammartin** [comment] 2015-05-13 14:13
The name dump_privatekey may refer to the fact that it is a private key scheme (public/private key pair)? I can confirm that I'm able to extract the public keys of x509 and x509 using this function. Neither x509 or x509req contains private keys.

**Comment by hynek** [comment] 2015-05-14 10:18
So what would be the fix?  Making sure only private keys are passed into it?

**Comment by alex** [comment] 2015-05-14 11:12
We should make sure that's really why it crashes, but yeah, I think so.
Segfaulting is bad :-)

On Thu, May 14, 2015 at 6:18 AM, Hynek Schlawack <notifications@github.com>
wrote:

> So what would be the fix? Making sure only private keys are passed into it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/pyopenssl/issues/259#issuecomment-101995061>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by abrahammartin** [comment] 2015-05-14 11:32
Is there any other function to extract the public key from a x509 and/or x509req? If the answer is yes, I have missed it / didn't found in the documentation. If the answer is no, it is a must and should be created if the dump_privatekey function is restricted only to private keys.

**Comment by reaperhulk** [comment] 2015-05-14 15:06
You can extract the public key from an X509 certificate or req by loading it and calling `get_pubkey`

**Comment by abrahammartin** [comment] 2015-05-14 15:13
Yes, I know that, but that gives you a PKey object. dump_privatekey transforms this PKey object into a FILETYPE_TEXT, FILETYPE_PEM, or FILETYPE_ASN1 text representation. This is why I said that I suspect that the name "privatekey" in "dump_privatekey" may refer to the fact that PKey is a key of a private key scheme (public/private key pair).

**Comment by reaperhulk** [comment] 2015-05-14 15:49
Ah, I see. Yeah it looks like there needs to be a dump_publickey (and dump_privatekey does RSA specific things when passing FILETYPE_TEXT so arguably that should be fixed too...unless pyopenssl doesn't support DSA/EC).

**Comment by abrahammartin** [comment] 2015-05-14 16:10
I have a database with thousands of x509 and x509req and surprisingly very few of them segfaulted, most of them worked ok with this code.

**Comment by reaperhulk** [comment] 2017-06-29 22:52
I can't replicate this with a current OpenSSL (1.1.0f). The reproducer provided by Alex gives

```Error: [('digital envelope routines', 'EVP_PKEY_get0_RSA', 'expecting an rsa key')]```

This is because FILETYPE_TEXT has this code path:

```
        rsa = _ffi.gc(
            _lib.EVP_PKEY_get1_RSA(pkey._pkey),
            _lib.RSA_free
        )
        result_code = _lib.RSA_print(bio, rsa, 0)
```

This is ridiculous, but we really shouldn't support FILETYPE_TEXT anyway. I think the way forward here (given our goal of making pyOpenSSL obsolete, and especially since X509 is better handled by pyca/cryptography) is to check the key type and raise a TypeError if you call dump_privatekey with FILETYPE_TEXT with anything other than an RSA key. PR coming :)

**Closed** 2017-06-29 23:43 UTC
