### ISSUE TITLE
Multiple tests have race conditions

### ISSUE THREAD

**Issue by hynek** [pyca/pyopenssl#266] opened 2015-05-26 17:28 UTC
They compare outputs and if the data is generate around the boundary of a second, they don’t match because of that.

Currently known perpetrators:
- [ ] `CRLTests.test_export_text`
- [ ] `X509Tests.test_gmtime_adj_notBefore`
- [ ] `test_ssl.ConnectionTests.test_state_string`

**Comment by alexwlchan** [comment] 2016-12-21 07:49
Duplicate of #102?

**Comment by alexwlchan** [comment] 2016-12-21 07:54
I’ve been thinking about this a bit, because I’ve been racking up a lot of CI runs lately.

The most “pure”, robust approach would be to modify the test to detect datestamps in the two strings, parse as datetime, get a timedelta object, re-run as necessary… which all seems rather fiddly and complicated for a window condition that usually disappears if we re-run the test.

Alternatively, how would you feel about using [flaky](https://pypi.python.org/pypi/flaky) to re-run those tests a second time if we detect an AssertionError thrown on the first run? That’s easy to do and would probably catch the vast majority of cases.

**Comment by hynek** [comment] 2016-12-21 08:14
I *think* I’d prefer the pure approach TBH.  Although I’m a bit afraid, the timestamp format might change with OpenSSL versions (just a hunch based on history)?

**Comment by alex** [comment] 2017-07-07 03:01
`test_export_text` is probably the most frequent offender here. I'm sorely tempted to slap `flaky` on it. How are other folks feeling?

**Comment by reaperhulk** [comment] 2017-07-07 03:10
I'm 👍 on flaky. Tired of pyOpenSSL failing parts of cryptography's CI with its races...

**Closed** 2017-07-07 03:43 UTC
