### ISSUE TITLE
exceptions.AttributeError: 'X509' object has no attribute '_subject_invalidator'

### ISSUE THREAD

**Issue by stuertz** [pyca/pyopenssl#724] opened 2017-11-30 08:59 UTC
Hi,
I ran into the following traceback using 
* windows
* Python 2.7
* Twisted 17.9.0 
* pyOpenSSL-17.4.0-py2.7
* OpenSSL 1.0.2m  2 Nov 2017

pyopenssl ist build on my own from setup.py and linked above OpenSSL Version.

Any help would be appreciated.

```
	Traceback (most recent call last):
	  File "c:\work\src\trunk\win32\debug\img\lib\site-packages\twisted-17.9.0-py2.7-win32.egg\twisted\python\log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "c:\work\src\trunk\win32\debug\img\lib\site-packages\twisted-17.9.0-py2.7-win32.egg\twisted\python\log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "c:\work\src\trunk\win32\debug\img\lib\site-packages\twisted-17.9.0-py2.7-win32.egg\twisted\python\context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "c:\work\src\trunk\win32\debug\img\lib\site-packages\twisted-17.9.0-py2.7-win32.egg\twisted\python\context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "c:\work\src\trunk\win32\debug\img\lib\site-packages\twisted-17.9.0-py2.7-win32.egg\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "c:\work\src\trunk\win32\debug\img\lib\site-packages\twisted-17.9.0-py2.7-win32.egg\twisted\internet\tcp.py", line 205, in doRead
	    return self._dataReceived(data)
	  File "c:\work\src\trunk\win32\debug\img\lib\site-packages\twisted-17.9.0-py2.7-win32.egg\twisted\internet\tcp.py", line 211, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "c:\work\src\trunk\win32\debug\img\lib\site-packages\twisted-17.9.0-py2.7-win32.egg\twisted\protocols\tls.py", line 315, in dataReceived
	    self._checkHandshakeStatus()
	  File "c:\work\src\trunk\win32\debug\img\lib\site-packages\twisted-17.9.0-py2.7-win32.egg\twisted\protocols\tls.py", line 235, in _checkHandshakeStatus
	    self._tlsConnection.do_handshake()
	  File "build\bdist.win32\egg\OpenSSL\SSL.py", line 1716, in do_handshake
	    
	  File "build\bdist.win32\egg\OpenSSL\SSL.py", line 1419, in _raise_ssl_error
	    
	  File "build\bdist.win32\egg\OpenSSL\SSL.py", line 209, in raise_if_problem
	    
	exceptions.AttributeError: 'X509' object has no attribute '_subject_invalidator'
```

**Comment by reaperhulk** [comment] 2017-11-30 09:12
This is a duplicate of #722 (and fixed when PR #723 merges)

We'll be releasing a version with the fix within the next 24 hours.

Thanks for the report!

**Closed by reaperhulk** 2017-11-30 09:12 UTC
